server:
  port: 9192
spring:
  datasource:
    username: admin
    password: password
    url: jdbc:mysql://employeems.czagg4e06hak.eu-north-1.rds.amazonaws.com:3306/employeeMS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

